solr_url:
  url: "https://golr.geneontology.org/solr/"
  timeout: 30
ontologies:
  - id: go
    handle: go
    pre_load: false
sparql_url:
  url: "https://rdf.geneontology.org/sparql"
  timeout: 60
#gocam_provided_by_index_file:
#    url: "https://go-data-product-live-go-cam.s3.us-east-1.amazonaws.com/product/json/providedBy_index.json"
#    timeout: 30
gocam_contributor_index_file:
    url: "/tmp/test-output/contributor_index.json"
    # url: "https://go-data-product-live-go-cam.s3.us-east-1.amazonaws.com/product/json/contributor_index.json"
    timeout: 30
#gocam_entity_index_file:
#    url: "https://go-data-product-live-go-cam.s3.us-east-1.amazonaws.com/product/json/entity_index.json"
#    timeout: 30
#gocam_term_index_file:
#    url: "https://go-data-product-live-go-cam.s3.us-east-1.amazonaws.com/product/json/source_index.json"
#    timeout: 30
#gocam_evidence_index_file:
#    url: "https://go-data-product-live-go-cam.s3.us-east-1.amazonaws.com/product/json/evidence_index.json"
#    timeout: 30
gocam_historical_index_file:
    url: "https://go-data-product-live-go-cam.s3.us-east-1.amazonaws.com/product/json/provider-to-model.json"
    timeout: 30
